version: "3.8"

services:
  backend:
    restart: always
    build:
      context: .
      target: backend
    env_file:
      - src/.env
    command: "uvicorn main:app --host 0.0.0.0 --port 8000"
    volumes:
      - "C:/Users/misha/log:/code/src/logs/"
    ports:
    - "8000:8000"
    networks:
      backend:


  postgres:
    restart: always
    image: postgres:13-alpine
    container_name: postgres
    env_file:
      - src/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      backend:


volumes:
  postgres_data:
  log:

networks:
  backend: